### ISSUE TITLE
Mesh Deform and Surface Deform support?

### ISSUE THREAD

**Issue by aVersionOfReality** [ScottishCyclops/tensionmap#9] opened 2019-06-05 20:20 UTC
Would it be possible to get support for the Mesh Deform and Surface Deform modifiers? My character rig uses a deform cage to control most of the body and clothing, with an armature controlling the deform cage. Currently I'd need to transfer the vertex colors from the deform cage to the deformed objects, which costs accuracy.

An option for the tension map to update on render and frame change would also be great!

**Comment by ScottishCyclops** [comment] 2019-06-07 20:08
Hey !

I plan on implementing a way to manually select which modifier is used when calculating the tension map.
Currently, only the modifiers types listed [at the top of the script](https://github.com/ScottishCyclops/tensionmap/blob/master/tensionmap.py#L37) are taken into account.
As a "quick fix", you can add to that list the names of the modifiers (taken from this site: https://docs.blender.org/api/blender2.8/bpy.types.Modifier.html#bpy.types.Modifier.type), then reload the addon in Blender.

> An option for the tension map to update on render and frame change would also be great!

I'm note sure I understand. Currently, the tension map updates on frame change for all objects, as well as manually for a single object when you click on the operator "Update Tension Map".

Does it not update on render ? Please tell me more :)

Thanks for your comment

**Comment by ScottishCyclops** [comment] 2019-06-08 00:06
> An option for the tension map to update on render and frame change would also be great

I think I understand what you mean now x)

An option to enable/disable the update of tensionmap on frame change would be useful. I need to decide if a global option is best, or an option for each mesh...

If you wish, open a separate issue to discuss that feature :)

**Comment by aVersionOfReality** [comment] 2019-06-08 05:02
Thanks for the response!

It looks like MESH_DEFORM is in the kept_modifiers by default. I assumed it didn't work because it wasn't working on my character, and I jumped to the conclusion that it wasn't supported. But now I'm testing it in a new file on a simple object, and it does seem to be working. So it not working is somehow specific to my character setup, and my report here is incorrect!

I also see that it does update the tension map on frame change and on f12 render. I had missed this too apparently due to issues in my character file. I'll try to narrow down what they are. Sorry for the misinformed request!

EDIT: Looks like it was because I had a mirror modifier on, which makes sense. It's working now.
EDIT 2: Worth noting that it doesn't work that well with the deform cage. I get better results transferring the tension on the cage to the clothing inside than using it on the clothing itself. If there's a better place to discuss this let me know and I'll show what's happening.

**Comment by ScottishCyclops** [comment] 2019-06-08 15:25
Since the topic is called *Mesh Deform and Surface Deform support?*, feel free to discuss it here.
I'm interested ! I haven't seen much "complex" usage of this Addon yet.

I don't quite get what you mean by:
> I get better results transferring the tension on the cage to the clothing inside

Also just to be clear, are you using 2.80 or 2.79 ?

**Comment by aVersionOfReality** [comment] 2019-06-08 17:59
Blender version is 2.8. I'm using the tension to control the Displacement Scale of procedural wrinkles around the joints on a tight outfit. The setup is a fairly low poly, optimized deform cage, and then a full detail mesh inside it. Here's a picture showing the tension the outfit gets on the mesh, vs the tension being transferred from the deform cage. Pictured is the Stretch. The amount generated on the mesh itself is so low its almost imperceptible. The amount coming in from the deform cage is probably higher than it should be, but these values are subjective so it doesn't really matter. I'm transferring it with Data Transfer's Projected Face Interpolated, so its getting smoothed out a bit and hits a wider area than is probably accurate. This doesn't matter for my setup since I have a vertex color mask limiting what areas are effected by the wrinkles anyway.

![Rei1_wip-11_tensionMapTest](https://user-images.githubusercontent.com/36803956/59150678-dd96c700-89db-11e9-9797-b53672b1234d.png)

As you can see, the deform cage is much lower poly, so there's a lot of stretch taking place on a lower amount of faces. I assume this is leading to the higher stretch values. I also have Corrective Smooth modifiers on both the deform cage and suit, and these aren't in the script's allowed list. I'll need to test adding them. I'm not currently using Surface Deform for this project, but i'll test out enabling it later on and see how it behaves. But for now this setup is actually working out for this project at least.

Thanks again for developing this tool!

**Comment by ScottishCyclops** [comment] 2019-06-09 17:39
In any case I assume generating tension on the Deform Cage is much faster. But of course, if you are not concerned about speed, generating it on the actual mesh would be better.

have you tried increasing the "Multiplier" when applying on the mesh ? Since you're telling me the values aren't zero, multiplying them should result in some data.

I tried to reproduce your situation in a simple file.
But it works x) Can you take a look at the following file and see if I missed something from your setup ?

[tension-test.zip](https://github.com/ScottishCyclops/tensionmap/files/3269786/tension-test.zip)

**Comment by ScottishCyclops** [comment] 2019-12-19 14:29
I'm closing this issue since It's been some time without any feedback.
Feel free to open a new one if you still have trouble with the add-on.

**Closed as completed by ScottishCyclops** 2019-12-19 14:29 UTC
Labels: enhancement
