### ISSUE TITLE
2.81

### ISSUE THREAD

**Issue by FilmReale** [ScottishCyclops/tensionmap#16] opened 2020-01-22 13:45 UTC
Neither the main version nor the numba version appear to work in version 2.81 of blender.  The tm_tension vertex colors only writes to the green channel and it just looks darker when vertices are closer to each-other in the base mesh (irrespective of any transformations on the mesh from an armature).  LMK if that makes sense.

**Comment by ScottishCyclops** [comment] 2020-01-22 15:25
Thank you very much for the report.
It makes sense, and I'm able to reproduce the bug. It is very weird.
I'll investigate as soon as possible.

Scott

**Comment by VincentKueszter** [comment] 2020-01-26 10:29
That's strange. I have 2.81 as well and I can't reproduce that, at least with the main branch.
What's the exact version you have? Technically I have 2.81a, maybe that's the reason.
Exact version: 
> version: 2.81 (sub 16), branch: master, commit date: 2019-11-20 14:27, hash: 26bd5ebd42e3, type: Release
> build date: 2019-11-20, 16:33:00

(Via Help -> Save System Info)

**Comment by FilmReale** [comment] 2020-01-26 12:25
Hi @VincentKueszter ... here is my version info:

version: 2.81 (sub 16), branch: master, commit date: 2019-12-04 11:32, hash: f1aa4d18d49d, type: Release
build date: 2019-12-04, 14:30:40
platform: Windows

**Comment by ScottishCyclops** [comment] 2020-01-26 18:06
I tested again and the bug is "gone".
Here is my theory: Are you testing with a simple cube with loop cuts vertically ? Because when I make such an object, the behaviour you describe is happening.
However, with a cylinder, or any other more complex object, the add-on behaves as expected.

Can you test on a cylinder or any complex object ?

Scott

**Comment by FilmReale** [comment] 2020-01-26 18:47
Ok I made a cylinder shape and got the script to work.

However my other model (which is a complex creature that looks like a giant floating snake thing) still doesn't work.  That object was originally built off of a cube I think, but now is complicated and organic in design.  The script has worked on this creature before but only stopped with the newest version. LMK your thoughts.

**Comment by ScottishCyclops** [comment] 2020-01-26 22:02
It is very weird. Maybe the topology is not suited to the computation (the same way the cube wasn't), but if you say it used to work, then it is really weird.
Can you tell me which version of the addon it worked on, so I can try to see if there were breaking changes ?

**Comment by FilmReale** [comment] 2020-01-27 02:14
Ok I think I figured it out?  

- I made a new project in the newest version of Blender I have with the numba version of the tension script enabled.
- Then I imported an older version of my model, and the plugin worked.
- When I imported the newer version of my model, IT DID NOT WORK.
- The later version of the model had a shape key applied. 
- Apparently if there is a shape key within spitting distance of this plugin, it won't work.  I figured that the lack of shape key support (that was talked about elsewhere on the page) was more about it not including shape keys in the deform math or something like that, but in my case anyway, just having a shape key made the plugin fail.
LMK if that is reproducible or if I'm on the wrong track here.

**Comment by FilmReale** [comment] 2020-01-27 02:41
That said I'm guessing that the shape key is the reason the model is now incompatible with the plugin, but I'm not sure.

**Comment by ScottishCyclops** [comment] 2020-01-30 06:08
Thank your for investigating.
I tried implementing shape keys the other night and found out the following:

Since they are linked to a mesh, when computing the deformed mesh, shape keys are ignored in the math, as if they where not there.
So it turns out it's hard to implement support for them, because Blender doesn't simply allow you to "apply a shape key's transform".
But that also means that any mesh with a shape key with any value other than 0 could generate unwanted results, because it acts as if it wasn't there.

I hope to solve shape keys, which should fix the issue you are having, but I don't have any time frame to give you.
I'll close this issue since it's title doesn't match the actual problem, and add a note about shape keys in the readme.

Scott

**Closed as completed by ScottishCyclops** 2020-01-30 06:08 UTC
Labels: cannot_reproduce

**Comment by FilmReale** [comment] 2020-02-02 03:30
Ok thanks @ScottishCyclops .... I'm bummed that this plugin now won't work on my project, but I appreciate your answer and all you do.  For my purposes, I would prefer the plugin to apply the shape key but ignore the transformation caused by the shape key (if that makes sense).  My shape key de-ages the monster in question, so those deformations ideally would be applied before the base case is established for armature deformations (rather than treated like a deformation itself).  I kind of assumed that's what would happen without shapekey support, but it seems even having a shape key causes it fail.
